language: objective-c
before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - sudo motion update
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - (ruby --version)
script: >
  bundle exec rake clean &&
  bundle exec rake spec &&
  bundle exec rake clean &&
  bundle exec rake spec bits=64 &&
  bundle exec rake clean &&
# bundle exec rake spec platform=osx
# rake spec device_family='iPhone 4s' &&
# rake spec device_family='iPhone 5' &&
# rake spec device_family='iPad Air' &&
