language: objective-c
before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - sudo motion update
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - (ruby --version)
script: >
  rake clean &&
  rake spec &&
  rake clean &&
  rake spec platform=osx
